# Project
mod_version=1.7.0
group=org.cyclops.integratedterminals
java_version=25

# Common
minecraft_version=26.2
mod_name=IntegratedTerminals
mod_author=rubensworks (aka kroeser)
mod_id=integratedterminals
license=MIT
github_url=https://github.com/CyclopsMC/IntegratedTerminals
issue_tracker_url=https://github.com/CyclopsMC/IntegratedTerminals/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/integrated-terminals
description=Terminals for managing and overviewing Integrated Dynamics networks.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

curseforge_project_id=295910
modrinth_project_id=HmLJoQ1K

# NeoForge
neoforge_version=26.2.0.6-beta
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/integrated-terminals.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true

# Dependencies
cyclopscore_version=1.30.0-1038
integrateddynamics_version=1.33.4-1858
integratedterminalscompat_version=26.2-neoforge:1.0.0-173
integratedcrafting_version=1.4.7-586
integratedtunnels_version=1.9.6-708
commoncapabilities_version=2.11.8-360
