# Project
mod_version=1.6.31
group=org.cyclops.integratedterminals
java_version=25

# Common
minecraft_version=26.1.2
mod_name=IntegratedTerminals
mod_author=rubensworks (aka kroeser)
mod_id=integratedterminals
license=MIT
github_url=https://github.com/CyclopsMC/IntegratedTerminals
issue_tracker_url=https://github.com/CyclopsMC/IntegratedTerminals/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/integrated-terminals
description=Terminals for managing and overviewing Integrated Dynamics networks.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

curseforge_project_id=295910
modrinth_project_id=HmLJoQ1K

# NeoForge
neoforge_version=26.1.2.22-beta
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/integrated-terminals.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

# Dependencies
cyclopscore_version=1.29.5-1012
integrateddynamics_version=1.32.11-1809
integratedterminalscompat_version=26.1.1-neoforge:1.0.0-162
integratedcrafting_version=1.4.5-560
commoncapabilities_version=2.11.4-344
