mod_version=1.6.4
minecraft_version=1.19.2
forge_version=43.2.21
cyclopscore_version=1.19.4-495
integrateddynamics_version=1.19.2-1.25.1-1066
integratedterminalscompat_version=1.19.2-1.0.0-117
integratedcrafting_version=1.19.2-1.1.8-254
release_type=release
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

commoncapabilities_version=1.19.2-2.9.4-186

# Workaround for Spotless bug
# https://github.com/diffplug/spotless/issues/834
org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
