modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedTerminals/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-terminals"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedterminals"
version="${file.jarVersion}"
displayName="IntegratedTerminals"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-terminals.json"
description='''
Terminals for managing and overviewing Integrated Dynamics networks.
'''
[[dependencies.integratedterminals]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.12.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.10.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.8.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,]"
    ordering="NONE"
    side="BOTH"
