modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedTerminals/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-terminals"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedterminals"
version="${file.jarVersion}"
displayName="IntegratedTerminals"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-terminals.json"
description='''
Terminals for managing and overviewing Integrated Dynamics networks.
'''
[[dependencies.integratedterminals]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.17.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.15.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.9.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,]"
    ordering="NONE"
    side="BOTH"
