modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedTerminals/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-terminals"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedterminals"
version="${file.jarVersion}"
displayName="IntegratedTerminals"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-terminals.json"
description='''
Terminals for managing and overviewing Integrated Dynamics networks.
'''
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
[[dependencies.integratedterminals]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="integrateddynamics"
    type="required"
    versionRange="[1.16.7,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="commoncapabilities"
    type="required"
    versionRange="[2.9.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminals]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,]"
    ordering="NONE"
    side="BOTH"
